apiVersion: v1
kind: ConfigMap
metadata:
  name: podman-syft-config
data:
  #!/bin/bash
  DOMAIN: localhost
  NODE_NAME: default_node_name
  NODE_TYPE: domain
  FRONTEND_TARGET: grid-ui-production
  HTTP_PORT: 80
  HTTPS_PORT: 443
  NETWORK_NAME: omnet
  RELEASE: production

  # tls
  IGNORE_TLS_ERRORS: False
  TRAEFIK_TLS_CONF: ./traefik/dynamic-configurations
  TRAEFIK_TLS_CERTS: ./traefik/certs
  TRAEFIK_PUBLIC_NETWORK: traefik-public
  TRAEFIK_TAG: grid.openmined.org
  TRAEFIK_PUBLIC_TAG: traefik-public

  STACK_NAME: grid-openmined-org
  DOCKER_IMAGE_BACKEND: openmined/grid-backend
  DOCKER_IMAGE_FRONTEND: openmined/grid-frontend
  DOCKER_IMAGE_SVELTE: openmined/grid-svelte
  DOCKER_IMAGE_TRAEFIK: traefik
  TRAEFIK_VERSION: v2.8.1
  REDIS_VERSION: 6.2
  RABBITMQ_VERSION: 3
  SEAWEEDFS_VERSION: 3.59
  DOCKER_IMAGE_SEAWEEDFS: chrislusf/seaweedfs:3.55
  VERSION: 0.8.6-beta.1
  VERSION_HASH: unknown
  STACK_API_KEY: ""

  # Backend
  BACKEND_CORS_ORIGINS: '["http://localhost","http://localhost:4200","http://localhost:3000","http://localhost:8080","https://localhost","https://localhost:4200","https://localhost:3000","https://localhost:8080","http://dev.grid.openmined.org","https://stag.grid.openmined.org","https://grid.openmined.org"]'
  PROJECT_NAME: grid
  SECRET_KEY: changethis
  DEFAULT_ROOT_EMAIL: info@openmined.org
  DEFAULT_ROOT_PASSWORD: changethis
  SMTP_TLS: True
  SMTP_PORT: 587
  SMTP_HOST:
  SMTP_USER:
  SMTP_PASSWORD:
  EMAILS_FROM_EMAIL: info@openmined.org
  SERVER_HOST: "https://${DOMAIN}"
  NETWORK_CHECK_INTERVAL: 60
  DOMAIN_CHECK_INTERVAL: 60
  ASSOCIATION_TIMEOUT: 10
  USERS_OPEN_REGISTRATION: False
  DEV_MODE: False

  # New Service Flag
  USE_NEW_SERVICE: False

  # Frontend
  BACKEND_API_BASE_URL: "/api/v2"

  # SeaweedFS
  S3_ENDPOINT: "seaweedfs"
  S3_PORT: 8333
  S3_ROOT_USER: "admin"
  S3_ROOT_PWD: "admin"
  S3_REGION: "us-east-1"
  S3_PRESIGNED_TIMEOUT_SECS: 1800
  S3_VOLUME_SIZE_MB: 1024

  # Jax
  JAX_ENABLE_X64: True

  # Mongo
  MONGO_HOST: localhost
  MONGO_PORT: 27017
  MONGO_USERNAME: root
  MONGO_PASSWORD: example
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example

  # Redis
  REDIS_PORT: 6379
  REDIS_STORE_DB_ID: 0
  REDIS_LEDGER_DB_ID: 1
  REDIS_HOST: redis

  # System
  CONTAINER_HOST: podman
  RELATIVE_PATH: ""

  # Jaeger
  TRACE: False
  JAEGER_HOST: localhost
  JAEGER_PORT: 14268

  # Syft
  SYFT_TUTORIAL_MODE: False
  CREDENTIALS_VOLUME: credentials-data
  NODE_SIDE_TYPE: high

  # Worker
  USE_BLOB_STORAGE: False

  #Oblivious
  OBLV_ENABLED: false
  OBLV_KEY_PATH: "~/.oblv"
  OBLV_LOCALHOST_PORT: 3030

  # Registation
  ENABLE_SIGNUP: False
