version: "3.8"
services:
  tailscale:
    profiles:
      - vpn
    volumes:
      - ./vpn:/tailscale

  proxy:
    ports:
      - "8080"
    command:
      - "--api" # admin panel
      - "--api.insecure=true" # admin panel no password

  frontend:
    build:
      target: "grid-ui-development"
    volumes:
      - ./frontend:/app

  # svelte:
  #   volumes:
  #     - ./svelte:/app

  db:
    ports:
      - "5432"

  redis:
    ports:
      - "6379"

  queue:
    image: rabbitmq:3-management
    ports:
      - "5672"
      - "15672"
  jaeger:
    image: jaegertracing/all-in-one:1.36
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  backend:
    volumes:
      - ./backend/grid:/app/grid
      - ./backend/alembic:/app/alembic
      - ../syft:/app/syft
      - ./data/package-cache:/root/.cache
    command: /start-reload.sh

  backend_stream:
    volumes:
      - ./backend/grid:/app/grid
      - ./backend/alembic:/app/alembic
      - ../syft:/app/syft
      - ./data/package-cache:/root/.cache
    command: "/start-reload.sh"

  celeryworker:
    volumes:
      - ./backend/grid:/app/grid
      - ./backend/alembic:/app/alembic
      - ../syft:/app/syft
      - ./data/package-cache:/root/.cache
    command: "/worker-start-reload.sh"

  headscale:
    profiles:
      - network
    volumes:
      - ./vpn:/headscale
    ports:
      - "4000"

  seaweedfs:
    profiles:
      - blob-storage
    # volumes:
    #   - ./data/seaweedfs:/data
    ports:
      - "9333" # admin
      - "8888" # filer
      - "8333" # S3
