version: "3.8"
services:
  proxy:
    ports:
      - "8080"
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - "--api" # admin panel
      - "--api.insecure=true" # admin panel no password

  frontend:
    volumes:
      - ${RELATIVE_PATH}./frontend/src:/app/src
      - ${RELATIVE_PATH}./frontend/static:/app/static
      - ${RELATIVE_PATH}./frontend/svelte.config.js:/app/svelte.config.js
      - ${RELATIVE_PATH}./frontend/tsconfig.json:/app/tsconfig.json
      - ${RELATIVE_PATH}./frontend/vite.config.ts:/app/vite.config.ts
    environment:
      - FRONTEND_TARGET=grid-ui-development

  # redis:
  #   ports:
  #     - "6379"

  # queue:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "15672" # admin web port
  #     # - "5672" # AMQP port

  mongo:
    ports:
      - "27017"

  backend:
    volumes:
      - ${RELATIVE_PATH}./backend/grid:/app/grid
      - ${RELATIVE_PATH}../syft:/app/syft
      - ${RELATIVE_PATH}./data/package-cache:/root/.cache
    environment:
      - DEV_MODE=True
    stdin_open: true
    tty: true

  # backend_stream:
  #   volumes:
  #     - ${RELATIVE_PATH}./backend/grid:/app/grid
  #     - ${RELATIVE_PATH}../syft:/app/syft
  #     - ${RELATIVE_PATH}./data/package-cache:/root/.cache
  #   environment:
  #     - DEV_MODE=True

  # celeryworker:
  #   volumes:
  #     - ${RELATIVE_PATH}./backend/grid:/app/grid
  #     - ${RELATIVE_PATH}../syft/:/app/syft
  #     - ${RELATIVE_PATH}./data/package-cache:/root/.cache
  #   environment:
  #     - DEV_MODE=True

  seaweedfs:
    profiles:
      - blob-storage
    # volumes:
    #   - ./data/seaweedfs:/data
    ports:
      - "9333" # admin web port
      - "8888" # filer web port
      - "8333" # S3 API port
