version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  uvicorn.default:
    "()": uvicorn.logging.DefaultFormatter
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  uvicorn.access:
    "()": "uvicorn.logging.AccessFormatter"
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  uvicorn.default:
    formatter: uvicorn.default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  uvicorn.access:
    formatter: uvicorn.access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - uvicorn.default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - uvicorn.access
    propagate: no
root:
  level: INFO
  handlers:
    - default
