version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  hypercorn.default:
    "()": hypercorn.logging.DefaultFormatter
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  hypercorn.access:
    "()": "hypercorn.logging.AccessFormatter"
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  hypercorn.default:
    formatter: hypercorn.default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  hypercorn.access:
    formatter: hypercorn.access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  hypercorn.error:
    level: INFO
    handlers:
      - hypercorn.default
    propagate: no
  hypercorn.access:
    level: INFO
    handlers:
      - hypercorn.access
    propagate: no
root:
  level: INFO
  handlers:
    - default
