group: travis_latest
language: python
cache: pip
python:
  - 3.6
matrix:
  allow_failures:
    - python: nightly
    - python: pypy
    - python: pypy3
install:
  - sudo apt-get update
  - hash -r
  - pip3 install -r requirements.txt > build.log
  - pip3 install flake8
  #- pip3 install flake8-docstrings
  - pip3 install flake8-comprehensions
  - pip3 install pep8-naming
  - pip3 install -r dev-requirements.txt >> build.log
before_script:
  # stop the build if there are Python syntax errors or undefined
  # names
  - flake8 --config=.flake8 .
  - black --check --verbose .
  # exit-zero treats all errors as warnings.
  # diverting from the standard 79 character line length in
  # accordance with this:
  # https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds
  - flake8 . --count --exit-zero --statistics --select=E,F,W,C90
script:
  - coverage run -m pytest -v
  - cd docs
  - make html
  # - if grep -q "Traceback (most recent call last):" nb_to_md.txt; then false; else true; fi
notifications:
  on_success: change
  # `always` will be the setting below once code changes slow down
  on_failure: change

