group: travis_latest
language: python
cache: pip
python:
    #- 2.7
    - 3.6
    #- nightly
    #- pypy
    #- pypy3
matrix:
    allow_failures:
        - python: nightly
        - python: pypy
        - python: pypy3
install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch=0.3.1 scipy jupyter -c pytorch
    - source activate test-environment

    - pip install -r requirements.txt
    - pip install flake8
    - pip install flake8-docstrings
    - pip install pep8-naming
    - pip install torchvision
    - pip install tensorflow
    - pip install keras
    - python setup.py install
before_script:
    # stop the build if there are Python syntax errors or undefined
    # names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.
    # diverting from the standard 79 character line length in
    # accordance with this:
    # https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds
    - flake8 . --count --exit-zero --max-complexity=11 --max-line-length=100 --statistics
script:
    - python setup.py test
    - bash scripts/execute_notebooks.sh
    - if grep -q "Traceback (most recent call last):" nb_to_md.txt; then false; else true; fi
notifications:
    on_success: change
    # `always` will be the setting below once code changes slow down
    on_failure: change
