# =================================================================================
# Syft on GKE Cluster
#
# Server side  : high
# Automount  : NO
# Ingress    : gce
# Extras:
#  - BackendConfig for increased timeout
# =================================================================================

server:
  name: syft-gcp
  side: high

  # Skip intermediate registry & directly build & push container images to target registry
  # Useful when workload identity is setup
  useInternalRegistry: false

  # Resources set inline with c3-standard-4 machine type
  resources:
    requests:
      cpu: 2
      memory: "8Gi"
    limits:
      cpu: 4
      memory: "16Gi"

# =================================================================================

seaweedfs:
  storageSize: 100Gi

  # Resources set inline with c3-standard-4 machine type
  resources:
    requests:
      cpu: 2
      memory: "8Gi"
    limits:
      cpu: 4
      memory: "16Gi"

# =================================================================================

ingress:
  # GKE 1.28+ needs ingressClassName
  className: gce
  class: gce

# =================================================================================

proxy:
  resourcesPreset: medium

  # Use custom backend config for increased timeout
  serviceAnnotations:
    cloud.google.com/backend-config: '{"default": "custom-backend-config"}'

# =================================================================================

registry:
  resourcesPreset: medium

# =================================================================================

frontend:
  resourcesPreset: medium

# =================================================================================

postgres:
  resourcesPreset: large

# =================================================================================

extraResources:
  # Configure load balancer backend service
  # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#configuring_ingress_features_through_backendconfig_parameters
  - apiVersion: cloud.google.com/v1
    kind: BackendConfig
    metadata:
      name: custom-backend-config
    spec:
      timeoutSec: 1800
