apiVersion: v1
entries:
  syft:
  - apiVersion: v2
    appVersion: 0.8.4-beta.3
    created: "2023-12-10T17:06:06.120631761Z"
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: b64efa8529d82be56c6ab60487ed24420a5614d96d2509c1f93c1003eda71a54
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.4-beta.3.tgz
    version: 0.8.4-beta.3
  - apiVersion: v2
    appVersion: 0.8.4-beta.2
    created: "2023-12-10T17:06:06.120258589Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: d5a70ff3bad4e62fcaeab25009d69c2d96cb8a5a362ab442d7b5d98aeafc5d52
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.4-beta.2.tgz
    version: 0.8.4-beta.2
  - apiVersion: v2
    appVersion: 0.8.4-beta.1
    created: "2023-12-10T17:06:06.119681438Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: ca5a12f73acdd26c70675bcc2e9ea345836ddcd74b5b1a4d0b3449838e50cd15
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.4-beta.1.tgz
    version: 0.8.4-beta.1
  - apiVersion: v2
    appVersion: 0.8.3-beta.6
    created: "2023-12-10T17:06:06.119039086Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 126d0411170611573c965a7cd0691b2d53d32d62457b37cfb6b720bcb6a5930c
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.3-beta.6.tgz
    version: 0.8.3-beta.6
  - apiVersion: v2
    appVersion: 0.8.3-beta.5
    created: "2023-12-10T17:06:06.118424365Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 6fb34879b22cbae4290deb0fb2ade1da835b52ea2d2c9b0b602f252b90c5e5e9
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.3-beta.5.tgz
    version: 0.8.3-beta.5
  - apiVersion: v2
    appVersion: 0.8.3-beta.4
    created: "2023-12-10T17:06:06.117774268Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 970129d52942640ebe1fa83275e9226c1495db526e7d3d042b455d60a16ba783
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.3-beta.4.tgz
    version: 0.8.3-beta.4
  - apiVersion: v2
    appVersion: 0.8.3-beta.3
    created: "2023-12-10T17:06:06.116940872Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 9162bc14e40021b56111c3c9dbeba2596ce1ff469263b0a1e0a4679174c14ef7
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.3-beta.3.tgz
    version: 0.8.3-beta.3
  - apiVersion: v2
    appVersion: 0.8.3-beta.2
    created: "2023-12-10T17:06:06.11525835Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 9e2ec45777f9dff36fd4e8fb707ffa32dbb1b7db0cdb00cc0d3c0260b37286f4
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.3-beta.2.tgz
    version: 0.8.3-beta.2
  - apiVersion: v2
    appVersion: 0.8.3-beta.1
    created: "2023-12-10T17:06:06.114697018Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 3e36fae1b0072fc4a3846cb3536be19dd4b015d6725e734d2ec67c06d03cd56f
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.3-beta.1.tgz
    version: 0.8.3-beta.1
  - apiVersion: v2
    appVersion: 0.8.2
    created: "2023-12-10T17:06:06.114135636Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 2424c859609e30f02a7f941b0eca77911f25891a2cc38c342bc71279aca68821
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2.tgz
    version: 0.8.2
  - apiVersion: v2
    appVersion: 0.8.2-beta.60
    created: "2023-12-10T17:06:06.113468849Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: ca73f97c06904d8f8449ea3b62c21bc59deee1da54a23e0931bd09e79f38ffeb
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.60.tgz
    version: 0.8.2-beta.60
  - apiVersion: v2
    appVersion: 0.8.2-beta.59
    created: "2023-12-10T17:06:06.112795008Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: bd65ed7db6cac4583abcf974e3b4d1e18946ea627494ca64558dc2d97bf37999
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.59.tgz
    version: 0.8.2-beta.59
  - apiVersion: v2
    appVersion: 0.8.2-beta.58
    created: "2023-12-10T17:06:06.112120888Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: c9d89c050a4326e0b43caea0302a3c47011ff4c83ee196635879d99e50ee4aed
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.58.tgz
    version: 0.8.2-beta.58
  - apiVersion: v2
    appVersion: 0.8.2-beta.57
    created: "2023-12-10T17:06:06.111403216Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: a038f368398aad3b127d2e0a5ad4770365768b9f30afd966c059860870124b4d
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.57.tgz
    version: 0.8.2-beta.57
  - apiVersion: v2
    appVersion: 0.8.2-beta.56
    created: "2023-12-10T17:06:06.11071563Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 210e2ffad436b892001bc8acd0598dbb79041dc2e3dc8179e7359b317eed7d23
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.56.tgz
    version: 0.8.2-beta.56
  - apiVersion: v2
    appVersion: 0.8.2-beta.53
    created: "2023-12-10T17:06:06.107567746Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: ab91512010a81ca45ff65030c366c6d16873913199a5346013cd24ee6348df84
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.53.tgz
    version: 0.8.2-beta.53
  - apiVersion: v2
    appVersion: 0.8.2-beta.52
    created: "2023-12-10T17:06:06.106879499Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 9c12aaaf0a2c6fdbb5b644dd541d75d35690c291ed5df2eabc137dfcf4b88367
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.52.tgz
    version: 0.8.2-beta.52
  - apiVersion: v2
    appVersion: 0.8.2-beta.51
    created: "2023-12-10T17:06:06.106209967Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: e1bc4b1cae999b2210540e63c54b9265983bb2113f9f427ac1b6bac49ebf571e
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.51.tgz
    version: 0.8.2-beta.51
  - apiVersion: v2
    appVersion: 0.8.2-beta.50
    created: "2023-12-10T17:06:06.10553798Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 576298c0cc4a5db09977065dd33290b5d7d51b717cd63258a33a57c07b98597e
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.50.tgz
    version: 0.8.2-beta.50
  - apiVersion: v2
    appVersion: 0.8.2-beta.49
    created: "2023-12-10T17:06:06.104861985Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 1a631e202a75baeb846611536bfdb89eb53ff3cff62107ed679f50d70eca9660
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.49.tgz
    version: 0.8.2-beta.49
  - apiVersion: v2
    appVersion: 0.8.2-beta.48
    created: "2023-12-10T17:06:06.104166405Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 9991e594eef4df318e64af9dd546ccdffdc8489d253d6feac3a5c7b7226998c9
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.48.tgz
    version: 0.8.2-beta.48
  - apiVersion: v2
    appVersion: 0.8.2-beta.47
    created: "2023-12-10T17:06:06.103442772Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: cf58b548cac834cc407380bcfda134ab79d1330fbd942ed663b38fd042ba8a00
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.47.tgz
    version: 0.8.2-beta.47
  - apiVersion: v2
    appVersion: 0.8.2-beta.46
    created: "2023-12-10T17:06:06.102806731Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 8b92b97ec4fdd149ff78fdb0040ee1ec7af7737dd9cb67e6fb84c2228c1be6cb
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.46.tgz
    version: 0.8.2-beta.46
  - apiVersion: v2
    appVersion: 0.8.2-beta.45
    created: "2023-12-10T17:06:06.10148549Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 57c7a712db8616513a1921e7127b7166b4c776a3595c1e94112e8a67874d9c67
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.45.tgz
    version: 0.8.2-beta.45
  - apiVersion: v2
    appVersion: 0.8.2-beta.44
    created: "2023-12-10T17:06:06.100906104Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 4267aff4bfdde651072af23c4da565320a24ddc452ee62b815bcf2af0563fced
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.44.tgz
    version: 0.8.2-beta.44
  - apiVersion: v2
    appVersion: 0.8.2-beta.43
    created: "2023-12-10T17:06:06.100326319Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 0cf59d375012ea87f2e72d11501084d47848384d5887d61d36f87de59eb35c7b
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.43.tgz
    version: 0.8.2-beta.43
  - apiVersion: v2
    appVersion: 0.8.2-beta.41
    created: "2023-12-10T17:06:06.09875352Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 2cb82c05cf260d12dbc686ad7d219bfbbf1111d229cd7dfc58fffd0405e7d27f
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.41.tgz
    version: 0.8.2-beta.41
  - apiVersion: v2
    appVersion: 0.8.2-beta.40
    created: "2023-12-10T17:06:06.098049514Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 13509d464bd3f98b95dca5efacbc880e8a6efcefc5ca35d77d484f8891c0b06f
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.40.tgz
    version: 0.8.2-beta.40
  - apiVersion: v2
    appVersion: 0.8.2-beta.39
    created: "2023-12-10T17:06:06.09746009Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: e73c3d7dccb85df373201aa6447be8e324a34b12ef5b3ef9e0c5ac21fce44530
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.39.tgz
    version: 0.8.2-beta.39
  - apiVersion: v2
    appVersion: 0.8.2-beta.38
    created: "2023-12-10T17:06:06.096838957Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 85a41b375f6436994c7c363b8985addcf1540e354c542cd960d5cef24bda8159
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.38.tgz
    version: 0.8.2-beta.38
  - apiVersion: v2
    appVersion: 0.8.2-beta.37
    created: "2023-12-10T17:06:06.095704724Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: a7bfbe113d473c4edec3ffe69703633756207c8faeb9d41ac333616b97a085ce
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.37.tgz
    version: 0.8.2-beta.37
  - apiVersion: v2
    appVersion: 0.8.1
    created: "2023-12-10T17:06:06.094922052Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: d347f1c199309282b7451da10560b79d244c78cad33c8ba5c1337ac626446927
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1.tgz
    version: 0.8.1
generated: "2023-12-10T17:06:06.094187919Z"
