apiVersion: v1
entries:
  syft:
  - apiVersion: v2
    appVersion: 0.8.2-beta.56
    created: "2023-11-11T11:37:51.902408204Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 210e2ffad436b892001bc8acd0598dbb79041dc2e3dc8179e7359b317eed7d23
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.56.tgz
    version: 0.8.2-beta.56
  - apiVersion: v2
    appVersion: 0.8.2-beta.55
    created: "2023-11-11T11:37:51.901730093Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 5fc95afb6ebd029694d8b7d9e4270c2f6458d13e74a3e0ef27b39564dfe377e5
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.55.tgz
    version: 0.8.2-beta.55
  - apiVersion: v2
    appVersion: 0.8.2-beta.54
    created: "2023-11-11T11:37:51.900839426Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 58b872dbf50a04f7a2896561d7cbf148318e0ac0aeee336b799d16f26a5c9862
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.54.tgz
    version: 0.8.2-beta.54
  - apiVersion: v2
    appVersion: 0.8.2-beta.53
    created: "2023-11-11T11:37:51.899886684Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: ab91512010a81ca45ff65030c366c6d16873913199a5346013cd24ee6348df84
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.53.tgz
    version: 0.8.2-beta.53
  - apiVersion: v2
    appVersion: 0.8.2-beta.52
    created: "2023-11-11T11:37:51.899016625Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 9c12aaaf0a2c6fdbb5b644dd541d75d35690c291ed5df2eabc137dfcf4b88367
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.52.tgz
    version: 0.8.2-beta.52
  - apiVersion: v2
    appVersion: 0.8.2-beta.51
    created: "2023-11-11T11:37:51.898149242Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: e1bc4b1cae999b2210540e63c54b9265983bb2113f9f427ac1b6bac49ebf571e
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.51.tgz
    version: 0.8.2-beta.51
  - apiVersion: v2
    appVersion: 0.8.2-beta.50
    created: "2023-11-11T11:37:51.896649644Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 576298c0cc4a5db09977065dd33290b5d7d51b717cd63258a33a57c07b98597e
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.50.tgz
    version: 0.8.2-beta.50
  - apiVersion: v2
    appVersion: 0.8.2-beta.49
    created: "2023-11-11T11:37:51.895773134Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 1a631e202a75baeb846611536bfdb89eb53ff3cff62107ed679f50d70eca9660
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.49.tgz
    version: 0.8.2-beta.49
  - apiVersion: v2
    appVersion: 0.8.2-beta.48
    created: "2023-11-11T11:37:51.894889971Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 9991e594eef4df318e64af9dd546ccdffdc8489d253d6feac3a5c7b7226998c9
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.48.tgz
    version: 0.8.2-beta.48
  - apiVersion: v2
    appVersion: 0.8.2-beta.47
    created: "2023-11-11T11:37:51.894011026Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: cf58b548cac834cc407380bcfda134ab79d1330fbd942ed663b38fd042ba8a00
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.47.tgz
    version: 0.8.2-beta.47
  - apiVersion: v2
    appVersion: 0.8.2-beta.46
    created: "2023-11-11T11:37:51.892971814Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 8b92b97ec4fdd149ff78fdb0040ee1ec7af7737dd9cb67e6fb84c2228c1be6cb
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.46.tgz
    version: 0.8.2-beta.46
  - apiVersion: v2
    appVersion: 0.8.2-beta.45
    created: "2023-11-11T11:37:51.892225706Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 57c7a712db8616513a1921e7127b7166b4c776a3595c1e94112e8a67874d9c67
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.45.tgz
    version: 0.8.2-beta.45
  - apiVersion: v2
    appVersion: 0.8.2-beta.44
    created: "2023-11-11T11:37:51.891456936Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 4267aff4bfdde651072af23c4da565320a24ddc452ee62b815bcf2af0563fced
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.44.tgz
    version: 0.8.2-beta.44
  - apiVersion: v2
    appVersion: 0.8.2-beta.43
    created: "2023-11-11T11:37:51.89069062Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 0cf59d375012ea87f2e72d11501084d47848384d5887d61d36f87de59eb35c7b
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.43.tgz
    version: 0.8.2-beta.43
  - apiVersion: v2
    appVersion: 0.8.2-beta.42
    created: "2023-11-11T11:37:51.889382206Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: b0bebaa84e6e3588369ba9267169adb6e1f408f30be617e9b1f745a862fb4913
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.42.tgz
    version: 0.8.2-beta.42
  - apiVersion: v2
    appVersion: 0.8.2-beta.41
    created: "2023-11-11T11:37:51.887695248Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 2cb82c05cf260d12dbc686ad7d219bfbbf1111d229cd7dfc58fffd0405e7d27f
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.41.tgz
    version: 0.8.2-beta.41
  - apiVersion: v2
    appVersion: 0.8.2-beta.40
    created: "2023-11-11T11:37:51.886745372Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 13509d464bd3f98b95dca5efacbc880e8a6efcefc5ca35d77d484f8891c0b06f
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.40.tgz
    version: 0.8.2-beta.40
  - apiVersion: v2
    appVersion: 0.8.2-beta.39
    created: "2023-11-11T11:37:51.885984496Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: e73c3d7dccb85df373201aa6447be8e324a34b12ef5b3ef9e0c5ac21fce44530
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.39.tgz
    version: 0.8.2-beta.39
  - apiVersion: v2
    appVersion: 0.8.2-beta.38
    created: "2023-11-11T11:37:51.88524446Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: 85a41b375f6436994c7c363b8985addcf1540e354c542cd960d5cef24bda8159
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.38.tgz
    version: 0.8.2-beta.38
  - apiVersion: v2
    appVersion: 0.8.2-beta.37
    created: "2023-11-11T11:37:51.884437559Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.9.1
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: a7bfbe113d473c4edec3ffe69703633756207c8faeb9d41ac333616b97a085ce
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.2-beta.37.tgz
    version: 0.8.2-beta.37
  - apiVersion: v2
    appVersion: 0.8.1
    created: "2023-11-11T11:37:51.88358469Z"
    dependencies:
    - name: component-chart
      repository: https://charts.devspace.sh
      version: 0.8.6
    description: Perform numpy-like analysis on data that remains in someone elses
      server
    digest: d347f1c199309282b7451da10560b79d244c78cad33c8ba5c1337ac626446927
    icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png
    name: syft
    type: application
    urls:
    - https://openmined.github.io/PySyft/helm/syft-0.8.1.tgz
    version: 0.8.1
generated: "2023-11-11T11:37:51.882507156Z"
