---
- name: Install Tox
  shell: "runuser -l {{ om_user }} -c 'pip install tox"
  become: yes
  when: vagrant is not defined and install == "true" and jupyter == "true"

- name: Keep Jupyter Notebooks server running
  ansible.builtin.cron:
    disabled: "{{ not install | bool }}"
    name: "Jupyter Notebooks server"
    job: "{{ syft_dir }}/packages/grid/scripts/jupyter.sh {{ syft_dir }} {{ om_user }} {{ jupyter_token }}"
  become: yes
  when: vagrant is not defined and jupyter == "true"
