[build-system]
# AVOID CHANGING REQUIRES: IT WILL BE UPDATED BY PYSCAFFOLD!
requires      = ["setuptools>=46.1.0", "wheel", "read-version[toml]"]
build-backend = "setuptools.build_meta"

[tool.read_version.version]
path     = ["src/syft/VERSION"]
variable = "__version__"
