default_context:
  project_name: 'pygrid-domain'
  project_slug: 'pygrid-domain'
  domain_main: 'pygrid-domain.com'
  domain_staging: 'stag.pygrid-domain.com'
  docker_swarm_stack_name_main: 'pygrid-domain-com'
  docker_swarm_stack_name_staging: 'stag-pygrid-domain-com'
  secret_key: 'changethis'
  first_superuser: 'admin@pygrid-domain.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.pygrid-domain.com", "https://stag.pygrid-domain.com", "https://pygrid-domain.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@pygrid-domain.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@pygrid-domain.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'pygrid-domain.com'
  traefik_constraint_tag_staging: 'stag.pygrid-domain.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
