---
- name: Install System Packages
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
      - git
      - podman
      - podman-docker
    state: present
  become: true
# - name: Install required packages for building Python
#   ansible.builtin.shell: sudo dnf install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel make wget epel-release openssl11 openssl11-devel
# sqlite-devel
#   args:
#     executable: /bin/bash

# - name: Install required packages for building Python (Development Tools)
#   ansible.builtin.shell: sudo dnf groupinstall -y "Development Tools"
#   args:
#     executable: /bin/bash

# - name: Export CFLAGS and LDFLAGS environment variables
#   ansible.builtin.shell: export CFLAGS="$CFLAGS $(pkg-config --cflags openssl11)" LDFLAGS="$LDFLAGS $(pkg-config --libs openssl11)"
#   args:
#     executable: /bin/bash

# - name: Download Python 3.10.11 source code
#   get_url:
#     url: https://www.python.org/ftp/python/3.10.11/Python-3.10.11.tgz
#     dest: /tmp/Python-3.10.11.tgz
#     mode: '0644'

# - name: Extract Python 3.10.11 source code
#   unarchive:
#     src: /tmp/Python-3.10.11.tgz
#     dest: /tmp/
#     remote_src: yes

# - name: Configure Python 3.10.11 build
#   command: ./configure --enable-loadable-sqlite-extension
#   args:
#     chdir: /tmp/Python-3.10.11/

# - name: Build Python 3.10.11
#   command: make
#   args:
#     chdir: /tmp/Python-3.10.11/

# - name: Install Python 3.10.11
#   command: make altinstall
#   args:
#     chdir: /tmp/Python-3.10.11/

# - name: Create a symlink for Python 3.10.11
#   file:
#     src: /usr/local/bin/python3.10
#     dest: /usr/bin/python3.10
#     state: link

# - name: Cleanup downloaded source files
#   file:
#     path: "{{ item }}"
#     state: absent
#   loop:
#     - /tmp/Python-3.10.11.tgz
#     - /tmp/Python-3.10.11
