- name: Allow sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Create docker group
  group:
    name: "docker"
    state: present

- name: Create om group
  group:
    name: "{{ om_group }}"
    state: present

- name: Create om user
  user:
    name: "{{ om_user }}"
    createhome: yes
    groups:
      - "{{ om_group }}"
      - docker
# - name: Install required packages
#   dnf:
#     name:
#       - slirp4netns
#     state: present
#     autoremove: yes
#     update_cache: yes

# - name: Create rootless Podman user
#   user:
#     name: "{{ om_user }}"
#     comment: "Rootless user for running Podman"
#     create_home: yes
#     home: "{{ om_homedir }}"
#     shell: /bin/bash

# - name: Ensure subuid and subgid ranges are configured for the rootless user
#   lineinfile:
#     path: "{{ item.path }}"
#     state: present
#     regexp: "^{{ item.user }}"
#     line: "{{ item.user }}:{{ item.start_uid }}:{{ item.count }}"
#   loop:
#     - { user: '{{ om_user }}', start_uid: '100000', count: '65536', path: '/etc/subuid' }
#     - { user: '{{ om_user }}', start_uid: '100000', count: '65536', path: '/etc/subgid' }

# - name: Add required sysctl entries for rootless Podman
#   sysctl:
#     name: "{{ item.name }}"
#     value: "{{ item.value }}"
#     state: present
#     sysctl_set: yes
#     reload: yes
#   loop:
#     - { name: 'user.max_user_namespaces', value: '28633' }
#     - { name: 'kernel.unprivileged_userns_clone', value: '1' }

# - name: Configure Podman for the rootless user
#   become: no
#   become_user: "{{ om_user }}"
#   block:
#     - name: Create .config directory for {{ om_user }}
#       ansible.builtin.file:
#         path: "{{ om_homedir }}/.config"
#         state: directory
#         mode: "0755"

#     - name: Create .config/containers directory for {{ om_user }}
#       ansible.builtin.file:
#         path: "{{ om_homedir }}/.config/containers"
#         state: directory
#         mode: "0755"

#     - name: Configure Podman registries.conf for rootless user
#       copy:
#         src: /etc/containers/registries.conf
#         dest: "{{ om_homedir }}/.config/containers/registries.conf"
#         owner: "{{ om_user }}"
#         group: "{{ om_user }}"
#         mode: "0644"

#     - name: Configure Podman storage.conf for rootless user
#       copy:
#         src: /etc/containers/storage.conf
#         dest: "{{ om_homedir }}/.config/containers/storage.conf"
#         owner: "{{ om_user }}"
#         group: "{{ om_user }}"
#         mode: "0644"

#     - name: Add user to vagrant group
#       user:
#         name: "{{ om_user }}"
#         groups:
#           - vagrant
#         append: yes
#       when: vagrant is defined

#     - name: Add vagrant user to podman group
#       user:
#         name: "vagrant"
#         groups:
#           - podman
#           - vagrant
#           - om
#         append: yes
#       when: vagrant is defined
