http:
  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
    backend:
      loadBalancer:
        servers:
          - url: "http://proxy:8001"
    backend-stream:
      loadBalancer:
        servers:
          - url: "http://proxy:8011"
    seaweedfs:
      loadBalancer:
        servers:
          - url: "http://seaweedfs:8333"
    seaweedfsmount:
      loadBalancer:
        servers:
          - url: "http://seaweedfs:4001"
    headscale:
      loadBalancer:
        servers:
          - url: "http://headscale:8080"
  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: "frontend"
    backend:
      rule: "PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)"
      entryPoints:
        - web
      service: "backend"
    backend-stream:
      rule: "PathPrefix(`/api`) && PathPrefix(`/api/v1/syft/stream`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)"
      entryPoints:
        - web
      service: "backend-stream"
    blob-storage:
      rule: "PathPrefix(`/blob`)"
      entryPoints:
        - web
      service: "seaweedfs"
      middlewares:
        - "blob-storage-url"
        - "blob-storage-host"
    blob-storage-mount:
      rule: "PathPrefix(`/mount`)"
      entryPoints:
        - web
        - vpn
      service: "seaweedfsmount"
      middlewares:
        - "blob-storage-mount-url"
    vpn:
      rule: "PathPrefix(`/vpn`)"
      entryPoints:
        - web
        - vpn
      service: "headscale"
      middlewares:
        - "vpn-url"
    ping:
      rule: "PathPrefix(`/ping`)"
      entryPoints:
        - web
      service: "ping@internal"

  middlewares:
    # by rewriting the customrequestheaders.Host with the same host:port as the
    # code uses internally any S3 presigned urls will still validate
    blob-storage-host:
      headers:
        customrequestheaders:
          Host: seaweedfs:8333
    blob-storage-url:
      stripprefix:
        prefixes: /blob
        forceslash: true
    blob-storage-mount-url:
      stripprefix:
        prefixes: /mount
        forceslash: true
    vpn-url:
      stripprefix:
        prefixes: /vpn
        forceslash: true
