---
om_user: om
om_group: om
om_homedir: "/home/{{ om_user }}"
syft_dir: "/home/om/PySyft"
build_dir: "/home/om/build"
github_repo: OpenMined/PySyft.git
repo_branch: "0.6.0"
docker_compose_plugin_dir: ".docker/cli-plugins"
node_name: node
node_type: domain
root_user: root
root_homedir: "/{{ root_user }}"
docker_compose_url: https://github.com/docker/compose/releases/download/v2.3.4/docker-compose-linux-x86_64
tls: "false"
release: "production"
cert_store_path: "{{ om_homedir }}/certs"
upload_tls_key: ""
upload_tls_cert: ""
install: "true"
jupyter: "false"
docker_tag: "local"
