---
- name: Install Docker GPG Key
  apt_key:
    id: 7EA0A9C3F273FCD8
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install Docker Repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker Packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
    autoclean: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker Compose
  stat:
    path: "{{ om_homedir }}/{{ docker_compose_plugin_dir }}"
    get_checksum: no
    get_md5: no
    mime: no
  register: docker_cli_dir_present

- name: Create Docker Compose Plugin Dir
  file:
    path: "{{ om_homedir }}/{{ docker_compose_plugin_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ om_user }}"
    group: "{{ om_user }}"
  become: yes

- name: Download Docker CLI
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ om_homedir }}/{{ docker_compose_plugin_dir }}/docker-compose"
  when: docker_cli_dir_present.stat.exists == False

- name: Change permissions
  file:
    path: "{{ om_homedir }}/{{ docker_compose_plugin_dir }}/docker-compose"
    state: touch
    mode: a+x
    owner: "{{ om_user }}"
    group: "{{ om_user }}"
  become: yes

- name: Ensuring docker service is always running
  systemd:
    enabled: yes
    state: started
    name: docker
