---
- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 1

- name: Apply system changes
  import_tasks: system.yml
  when: deploy_only is not defined

- name: Install docker
  import_tasks: docker.yml
  when: deploy_only is not defined

- name: Clone PySyft Repo
  git:
    repo: "https://github.com/{{ github_repo }}"
    dest: "{{ syft_dir }}"
    version: "{{ repo_branch }}"
  become_user: "{{ om_user }}"
  ignore_errors: yes
  when: vagrant is not defined

- name: PySyft Repo Update Cron Job
  ansible.builtin.cron:
    name: "Update PySyft Repo"
    job: "{{ syft_dir }}/packages/grid/scripts/cron.sh {{ syft_dir }} {{ github_repo }} {{ repo_branch }} {{ om_user }} {{ om_group }} {{ node_type }} {{ node_name }}"
  become: yes
  when: vagrant is not defined
