apiVersion: v2
name: syft
description: Perform numpy-like analysis on data that remains in someone elses server
type: application
version: "0.8.3-beta.5"
appVersion: "0.8.3-beta.5"
icon: https://raw.githubusercontent.com/OpenMined/PySyft/dev/docs/img/title_syft_light.png