---
- name: Install System Packages
  package:
    name: "{{ item }}"
    state: present
    autoclean: yes
    update_cache: yes
  loop:
    - python3-pip
  when: aa_demo is defined and aa_demo == "true"

- name: Install HAGrid
  shell: "runuser -l {{ om_user }} -c 'pip install -U hagrid'"
  become: yes
  when: aa_demo is defined and aa_demo == "true"

- name: Install Syft
  shell: "runuser -l {{ om_user }} -c 'pip install --pre syft'"
  become: yes
  when: aa_demo is defined and aa_demo == "true"

- name: Create HAGrid PySyft src
  file:
    path: "{{ syft_dir }}/.tox/syft.jupyter/lib/python3.8/site-packages/hagrid"
    state: directory
    mode: "0775"
    owner: "{{ om_user }}"
    group: "{{ om_user }}"
  when: aa_demo is defined and aa_demo == "true"

- name: Clone PySyft Repo
  git:
    repo: "https://github.com/{{ github_repo }}"
    dest: "{{ syft_dir }}/.tox/syft.jupyter/lib/python3.8/site-packages/hagrid/PySyft"
    version: "{{ repo_branch }}"
    force: yes
  become_user: "{{ om_user }}"
  ignore_errors: yes
  when: aa_demo is defined and aa_demo == "true"

- name: Kill Docker Containers
  shell: "docker rm $(docker ps -qa) --force || true"
  become: yes
  ignore_errors: yes
  when: aa_demo is defined and aa_demo == "true"

- name: Start Docker Containers
  shell:
    cmd: runuser -l {{ om_user }} -c 'hagrid launch domain to docker:80 --tag=latest --tail=false'
  become: yes
  when: aa_demo is defined and aa_demo == "true"

- name: Kill Docker Containers
  shell: "docker rm $(docker ps -qa) --force || true"
  become: yes
  ignore_errors: yes
  when: aa_demo is defined and aa_demo == "true"
