name: Benchmark Test

on:
#  schedule:
#    - cron: "0 00 * * *" # 12am UTC, 5:30pm Indian, 9pm Brazil, 11am AEDT #Trigger commit
  workflow_dispatch:
    inputs:
      none:
        description: "Run Benchmarks Manually"
        required: false
jobs:
  run-benchmark:
    strategy:
      matrix:
        python-version: [3.9]
    runs-on: [self-hosted, linux]
    steps:
      - name: set permissions on work folder for self-runners
        run: |
          sudo chown -R $USER:$USER ~/actions-runner/_work/
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          pip install --upgrade --user pip

      - name: Install tox
        run: |
          pip install --upgrade tox

      - name: Run Benchmark
        run: |
         tox -e syft.benchmark