name: CD - Docs
on:
  workflow_dispatch:
    inputs:
      none:
        description: "Deploy Syft Documentation"
        required: false
  pull_request:
    branches: [dev]
    paths: [docs/]
  push:
    branches: [dev]
    paths: [docs/]

jobs:
  cd-docs:
    strategy:
      matrix:
        python-version: ["3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: |
          pip install --upgrade pip uv==0.1.28 tox tox-uv==1.5.1
          uv --version

      - name: Build the docs
        run: |
          tox -e syft.docs

      - name: Deploy the docs
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/build/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
