name: Nightlies

on:
  schedule:
    - cron: "0 00 * * *" # 12am UTC, 5:30pm Indian, 9pm Brazil, 11am AEDT
  workflow_dispatch:
    inputs:
      none:
        description: "Run Nightlies Tests Manually"
        required: false

jobs:
  call-pr-tests-linting:
    if: github.repository == 'OpenMined/PySyft' # don't run on forks
    uses: OpenMined/PySyft/.github/workflows/pr-tests-linting.yml@dev

  call-pr-tests-hagrid:
    if: github.repository == 'OpenMined/PySyft' # don't run on forks
    uses: OpenMined/PySyft/.github/workflows/pr-tests-hagrid.yml@dev

  call-pr-tests-syft:
    if: github.repository == 'OpenMined/PySyft' # don't run on forks
    uses: OpenMined/PySyft/.github/workflows/pr-tests-syft.yml@dev

  call-pr-tests-stack:
    if: github.repository == 'OpenMined/PySyft' # don't run on forks
    uses: OpenMined/PySyft/.github/workflows/pr-tests-stack.yml@dev
    secrets: inherit

  # call-pr-tests-stack-arm64:
  #   if: github.repository == 'OpenMined/PySyft' # don't run on forks
  #   uses: OpenMined/PySyft/.github/workflows/pr-tests-stack-arm64.yml@dev
  #   secrets: inherit

  call-pr-tests-stack-public:
    if: github.repository == 'OpenMined/PySyft' # don't run on forks
    uses: OpenMined/PySyft/.github/workflows/pr-tests-stack-public.yml@dev
    secrets: inherit

  call-container-scan:
    if: github.repository == 'OpenMined/PySyft' # don't run on forks
    uses: OpenMined/PySyft/.github/workflows/container-scan.yml@dev
    secrets: inherit

  # call-rhel-tests:
  #   if: github.repository == 'OpenMined/PySyft' # don't run on forks
  #   uses: OpenMined/PySyft/.github/workflows/rhel-tests.yml@dev
  #   secrets: inherit
