name: PR Tests - Helm Upgrade

on:
  pull_request:
    branches:
      - dev
    paths:
      - packages/grid/helm/syft/**

  workflow_dispatch:
    inputs:
      none:
        description: "Run helm upgrade"
        required: false

jobs:
  pr-tests-helm-upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        if: steps.changes.outputs.syft == 'true'
        run: |
          pip install --upgrade tox

      - name: Upgrade helm on latest beta
        run: |
          tox -e dev.k8s.start
          UPGRADE_TYPE=BetaToDev tox -e syft.test.helm.upgrade
          tox -e dev.k8s.destroy
