name: PR Tests - Helm Upgrade

on:
  push:
    paths:
      - .github/workflows/pr-tests-helm-upgrade.yml
      - tox.ini
      - packages/grid/helm/syft/**

  pull_request:
    branches:
      - dev
    paths:
      - packages/grid/helm/syft/**

  workflow_dispatch:
    inputs:
      none:
        description: "Run helm upgrade"
        required: false

concurrency:
  group: pr-tests-helm-upgrade
  cancel-in-progress: true

jobs:
  pr-tests-helm-upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew update

          # Install python deps
          pip install --upgrade pip
          pip install tox

          # Install kubernetes
          brew install helm k3d devspace kubectl

      - name: Setup cluster
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          tox -e dev.k8s.start

      - name: Upgrade helm chart
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          UPGRADE_TYPE=BetaToDev tox -e syft.test.helm.upgrade

      - name: Destroy cluster
        if: always()
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          tox -e dev.k8s.destroyall
