name: Rhel Podman Stack Tests

on:
  workflow_call:

  workflow_dispatch:
    inputs:
      none:
        description: "Run Version Tests Manually"
        required: false

jobs:
  podman-tests-stack:
    strategy:
      max-parallel: 99
      matrix:
        os: [om-ci-rhel-9]
        python-version: ["3.12"]
      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:
      - name: set permissions on work folder for self-runners
        run: |
          sudo chown -R $USER:$USER ~/actions-runner/_work/

      - uses: actions/checkout@v4

      - name: check python version
        run: |
          python${{matrix.python-version}} --version

      # - name: Check for file changes
      #   uses: dorny/paths-filter@v2
      #   id: changes
      #   with:
      #     base: ${{ github.ref }}
      #     token: ${{ github.token }}
      #     filters: .github/file-filters.yml

      - name: Install tox
        # if: steps.changes.outputs.stack == 'true'
        run: |
          pip${{matrix.python-version}} install -U tox

      - name: Run notebook tests
        #if: steps.changes.outputs.stack == 'true'
        run: |
          tox -e stack.test.podman
