name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: >
          This issue has been marked stale because it has been open 30 days with no activity. Leave
          a comment or remove the `stale` label to unmark it. Otherwise, this will be closed in 7
          days.
        stale-pr-message: >
          This pull request has been marked stale because it has been open 30 days with no activity.
          Leave a comment or remove the `stale` label to unmark it. Otherwise, this will be closed
          in 7 days.
        stale-issue-label: "stale"
        stale-pr-label: "stale"
        exempt-pr-labels: "epic"
        days-before-stale: 30
        days-before-close: 7
